### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by JTatum95** [wc-library/bibtable#8]
1. Open links in a new window (I assume the links are being built so it’s just a matter of adding a target attribute during that process)
2. Build a UI that lets our user pick a collection from their library and then generate the appropriate embed code for that collection.
3. Add a filter for the tags field.
4. Check if we can use one filter to filter on two fields (specifically Title and Abstract)

**Comment by JTatum95** [comment]
1 and 4 are completed.
2 is currently working, but requires multiple clicks to display the table.
3 should be implemented as a permanently hidden row on the column that can be searched from the all search field.

TODO: Bug when sorting on open extra divs.
Edit: bug might no longer be a problem after changing child rows.

**Comment by JTatum95** [comment]
2. Updated so that two clicks are no longer required, but in Firefox the table from the prior click is opened. In Chrome it works fully.
Edit: It is not properly waiting for the getData request to finish before loading. Upon reload after this has finished it will work.

**Comment by jeffnm** [comment]
Can we get a dropdown for the tags as a separate input next to the search box? That way the user can know which tags are available to filter by.

**Comment by JTatum95** [comment]
Yes, I should be able to do that. The only potential problem is that it seems very few items actually have associated tags.

**Comment by jeffnm** [comment]
I think more are being added, and they might be in some of the other collections.

**Comment by JTatum95** [comment]
All of these issues have been addressed and completed. Closing.
