### ISSUE TITLE
Status and next steps

### ISSUE THREAD

**Issue by JTatum95** [wc-library/bibtable#9]
As I am leaving for a few weeks, I wanted to leave a final update on this project. I have gotten most everything to work as intended. The items below are all that I believe is left to complete.

1. The login form: 
    - I am currently posting the data to login.php and properly verifying that the given API key is functional and that it matches the username or userID. 
    - After this, the redirection should go to collections.php, but it is not currently working. 
    - Additionally, the method of writing to the api_key.php file will work fine for one single user per server, but no more than that. We should use cookies.

2. The embed links to the table: 
    - I could not think of a way to do this that was both secure and reasonable. The issue with the links is that they would have both the API key and the userID (as well as collection key). These 3 items are needed in order to pull the data from the API and format it into a table unless there was a constantly refreshing permanent data store. 
    - These links could theoretically be obfuscated using base64 encoding, but this is very easily converted back to plaintext and not secure. 
    - Alternatively, the unreasonable yet secure strategy would be to create a database with a randomly generated and encrypted token that when looked up would be decrypted to match the collection key, API key, and userID.

3. Subcollections:
    - Subcollections need to be sorted by the parent-child relationship. I have added an id of the unique key for the collection to the table row and added the HTML for the row as a string to the $rows array. There is also a commented out first draft of a loop that with some tweaking might accomplish the reordering.

Thanks,
Jesse

**Comment by jeffnm** [comment]
I've been able to get this up on a server for testing. 

We noticed a few issues with one particular collection. 

The FL Paper Archive collection has two issues. 
1. The type array is missing "manuscript", so the type is filled in as N/A. 
2. The tags for that collection aren't being populated correctly. We end up with a single record having two tags and none of the others have any, despite having them in Zotero. We do see tags in the other collections.
